/**
 * Pure string generators for `cool-astro-forms init` (CLI-01, D5). No I/O
 * here — `cli.ts` owns reading/writing the filesystem and printing to
 * stdout; this module is the single source of truth for WHAT gets written
 * and printed, so the .env.example inventory and the config snippet can't
 * silently drift out of sync with each other or with the e2e test.
 */

/**
 * Full serverless-inclusive env inventory (05-VALIDATION.md "Serverless env
 * contract" + this plan's `<interfaces>` block). Every entry is commented
 * out by default — `init` never activates a feature on the host's behalf,
 * it only scaffolds the file the host edits. Var NAMES stay uncommented in
 * spirit (present as text) even though the assignment itself is commented,
 * so a grep/search for any of these names always finds them here.
 */
export function envExampleTemplate(): string {
  return `# cool-astro-forms — environment variables
# Generated by \`npx cool-astro-forms init\`. Copy to .env (or set these in
# your host's environment panel) and fill in only what you need — every
# variable below is OPTIONAL unless noted, and each feature this package
# ships stays fully inert until its own variables are set.

# ---- Storage (optional; SQLite on disk is the zero-config default) ----
# Path to the local SQLite database file.
# CAF_DB_PATH=data/forms.db

# ---- Admin UI (optional; enables /forms-admin) ----
# Setting this turns the admin login on.
# FORMS_ADMIN_PASSWORD=
# HMAC session-signing key. Auto-generated and persisted beside CAF_DB_PATH
# on first use if omitted (unless CAF_REQUIRE_EXPLICIT_SECRETS is set below).
# FORMS_ADMIN_SECRET=

# ---- Serverless / ephemeral filesystems (Vercel, Netlify, Cloudflare) ----
# Set to 1 on serverless: fails boot LOUDLY if a required secret below is
# missing, instead of silently generating one that would vanish on the next
# cold start (breaking signed sessions and unsubscribe links every deploy).
# CAF_REQUIRE_EXPLICIT_SECRETS=
# REQUIRED on serverless when CAF_REQUIRE_EXPLICIT_SECRETS=1 (see
# FORMS_ADMIN_SECRET above).
# REQUIRED on serverless when CAF_REQUIRE_EXPLICIT_SECRETS=1 AND recovery is
# enabled in your coolForms() config.
# CAF_RECOVERY_SECRET=

# ---- SMTP (optional; needed to send notification + recovery emails) ----
# EMAIL_HOST=
# EMAIL_PORT=
# EMAIL_USER=
# EMAIL_PASS=

# ---- IP geolocation (optional; overrides the ipwhois.io default) ----
# GEO_PROVIDER=

# ---- Bot mitigation: Cloudflare Turnstile (optional) ----
# TURNSTILE_SITE_KEY=
# TURNSTILE_SECRET_KEY=

# ---- Payments: Stripe (optional) ----
# STRIPE_SECRET_KEY=
# STRIPE_WEBHOOK_SECRET=

# ---- Payments: PayPal (optional) ----
# PAYPAL_CLIENT_ID=
# PAYPAL_CLIENT_SECRET=
# PAYPAL_ENV=
# PAYPAL_WEBHOOK_ID=

# ---- Google Drive file uploads (optional) ----
# GOOGLE_DRIVE_CLIENT_ID=
# GOOGLE_DRIVE_CLIENT_SECRET=
# GOOGLE_DRIVE_REFRESH_TOKEN=

# ---- Ops canary (optional) ----
# CANARY_TOKEN=

# ---- Serverless storage backend: Turso/libSQL (optional; only read when ----
# ---- storage.kind is set to 'turso' in your coolForms() config) ----
# CAF_TURSO_DATABASE_URL=
# CAF_TURSO_AUTH_TOKEN=
`;
}

/**
 * The `coolForms()` call to paste into `astro.config.mjs` — never written
 * to disk by `init` (D5: this package never edits astro.config.mjs), only
 * printed. `siteId`/`siteUrl`/`forms.<id>.notifyTo` have no `.default()` in
 * `config.ts` (fail-fast by design), so each is marked REQUIRED here —
 * this is exactly the config `astro add`'s empty-args codemod can't supply
 * (05-RESEARCH.md Pitfall 5).
 */
export function configSnippet(): string {
  return `// astro.config.mjs
import { defineConfig } from 'astro/config';
import coolForms from 'cool-astro-forms';

export default defineConfig({
  integrations: [
    coolForms({
      siteId: 'my-site',               // REQUIRED — unique id for this site
      siteUrl: 'https://example.com',  // REQUIRED — the abandon route's same-origin check depends on this
      forms: {
        contact: {
          notifyTo: 'you@example.com', // REQUIRED per form — where abandonment/lead emails for THIS form go
        },
        // Add one entry per data-caf key you tag below.
      },
    }),
  ],
});
`;
}

/**
 * Everything `init` prints after scaffolding: the `astro add` empty-args
 * caveat (05-RESEARCH.md Pitfall 5), the `data-caf` tagging instructions
 * (README "Analytics"/PKG-03), and docs links.
 */
export function postInitInstructions(): string {
  return `Next steps:

1. Wire the integration into astro.config.mjs:
   - Run \`astro add cool-astro-forms\` — Astro installs the package and
     inserts the import plus a BARE \`coolForms()\` call into your
     integrations array. That bare call has no config and will fail Zod
     validation on your next \`astro dev\`/\`astro build\` (siteId, siteUrl,
     and each form's notifyTo are required) — replace it with the snippet
     printed above before running Astro again.
   - Or skip \`astro add\` and paste the snippet above manually if you'd
     rather not run Astro's codemod at all.

2. Tag every form you want tracked with a \`data-caf\` attribute matching a
   key in your \`forms\` config, e.g.:
     <form data-caf="contact"> ... </form>
   Add \`data-caf-ignore\` to any field inside the form you don't want
   captured.

3. Fill in .env.example for the features you want, then rename it to .env
   (or set the same keys in your host's environment panel) — every one is
   optional and its feature stays inert until its variables are set.

4. Deploying behind a proxy (Hostinger, Passenger, most production hosts)?
   Add your real domain to astro.config.mjs or every urlencoded form POST
   to a server route (starting with the /forms-admin login) fails with
   "403 Cross-site POST form submissions are forbidden":
     security: {
       allowedDomains: [{ hostname: 'example.com', protocol: 'https' }],
     },

Docs:
  - README / quickstart:  https://github.com/nipun-arora/cool-astro-forms#readme
  - Payments setup:       https://github.com/nipun-arora/cool-astro-forms/blob/main/docs/payments.md
  - Google Drive uploads: https://github.com/nipun-arora/cool-astro-forms/blob/main/docs/drive.md
  - Lead recovery:        https://github.com/nipun-arora/cool-astro-forms/blob/main/docs/recovery.md
  - Serverless deploys:   https://github.com/nipun-arora/cool-astro-forms/blob/main/docs/serverless.md
  - GDPR mechanics:       https://github.com/nipun-arora/cool-astro-forms/blob/main/docs/gdpr.md
`;
}
